// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP2CDPIwxIGJ6pB5MFVTCHlI3WjutamAA',
    appId: '1:1009838230573:web:159dca571511dee1937ca4',
    messagingSenderId: '1009838230573',
    projectId: 'genuis-africrypt',
    authDomain: 'genuis-africrypt.firebaseapp.com',
    storageBucket: 'genuis-africrypt.appspot.com',
    measurementId: 'G-BPYZH6X3P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC62vwauhxoW27z3RE-5n_LFHTc8qEUDT0',
    appId: '1:1009838230573:android:a76d60141d5855f7937ca4',
    messagingSenderId: '1009838230573',
    projectId: 'genuis-africrypt',
    storageBucket: 'genuis-africrypt.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP2CDPIwxIGJ6pB5MFVTCHlI3WjutamAA',
    appId: '1:1009838230573:web:7ac2f0ea0c0add43937ca4',
    messagingSenderId: '1009838230573',
    projectId: 'genuis-africrypt',
    authDomain: 'genuis-africrypt.firebaseapp.com',
    storageBucket: 'genuis-africrypt.appspot.com',
    measurementId: 'G-Z0HYVEQGKP',
  );
}
